# Generated by Django 4.1.5 on 2023-02-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=40)),
                ('camada', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='imagenes')),
            ],
        ),
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('fecha_de_entrega', models.DateField()),
                ('entregado', models.BooleanField()),
                ('imagen', models.ImageField(null=True, upload_to='imagenes')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes')),
            ],
        ),
        migrations.CreateModel(
            name='Opiniones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(default='', max_length=40)),
                ('cursos', models.CharField(max_length=40)),
                ('año', models.IntegerField()),
                ('docente', models.CharField(max_length=40)),
                ('calificacion', models.FloatField()),
                ('opinion', models.TextField(max_length=240)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('profesion', models.CharField(max_length=30)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes')),
            ],
        ),
    ]
