# Generated by Django 4.1.5 on 2023-02-19 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppColegio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregable',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='opiniones',
            name='imagen',
        ),
    ]
