# Generated by Django 4.1.5 on 2023-02-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppColegio', '0003_cliente_empleados_entregables_postulaciones_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postulaciones',
        ),
        migrations.RemoveField(
            model_name='opiniones',
            name='año',
        ),
        migrations.RemoveField(
            model_name='opiniones',
            name='cursos',
        ),
        migrations.RemoveField(
            model_name='opiniones',
            name='docente',
        ),
        migrations.AlterField(
            model_name='opiniones',
            name='calificacion',
            field=models.IntegerField(),
        ),
    ]
